# Generated by Django 5.2 on 2025-05-30 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usergame',
            unique_together={('game',)},
        ),
        migrations.RemoveField(
            model_name='usergame',
            name='user',
        ),
    ]
